//
// Created by Alexey Mihailov
//

#ifndef NERP_BUILDER_NBWXFORMELEMENTBLOCKOBJECT_H
#define NERP_BUILDER_NBWXFORMELEMENTBLOCKOBJECT_H


class nbWxFormElementBlockObject {

};


#endif //NERP_BUILDER_NBWXFORMELEMENTBLOCKOBJECT_H
