//
// Created by Alexey Mihailov
//

#ifndef NERP_BUILDER_NBWXPROJECTOPENEDSIMPLE_H
#define NERP_BUILDER_NBWXPROJECTOPENEDSIMPLE_H


class nbWxProjectOpenedSimple {

};


#endif //NERP_BUILDER_NBWXPROJECTOPENEDSIMPLE_H
